on:
  pull_request:
    types:
      - closed
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.describe.outputs.tagname }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-tags: true
          # fetch-depth: 0
      # - name: stinky but
      #   run: git sparse-checkout disable; git checkout origin/main
      - name: status
        run: git status
      - name: descibe
        run: git fetch --shallow-since "1 year" --tags --recurse-submodules=no
      - name: status
        run: git status
      - name: descibe
        run: git describe --tags
      - name: show refs
        run: find .git/refs
      # - name: peepee poopoo
      #   run: git checkout --progress --force -B main refs/remotes/origin/main
      - name: Get git describe for prerelease
        id: describe
        run: echo "tagname=pre-$(git describe --tags main)" >> $GITHUB_OUTPUT
      - name: show describe
        run: echo ${{ steps.describe.outputs.tagname }}